name = "pro-escala"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "pro-escala"
database_id = "COLOQUE_AQUI_O_ID_DO_D1_APOS_CRIAR"
