name = "pro-escala"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "pro-escala"
database_id = "544ed6d8-9c18-4bfb-bc5c-f8dc0aafb490"
